export { default as arrow } from "./arrow.svg";
export { default as lightModeIcon } from "./light-mode-icon.svg";
export { default as darkModeIcon } from "./dark-mode-icon.svg";
export { default as frame } from "./frame.svg";
export { default as star } from "./star.svg";
export { default as whiteButtonArrow } from "./white-button-arrow.svg";
export { default as tick } from "./tick.svg";
export { default as customGraphic } from "./custom-graphic.svg";
export { default as pageNotFound } from "./not-found-page-graphic.svg";
